const state={lang:localStorage.getItem("karhutlaDashboardLang")||"en",data:null,charts:{}};
const I18N={en:{
eyebrow:"FOREST & LAND FIRE IMPACT ANALYTICS",title:"Karhutla Indonesia 2026",headerDescription:"Situation, fire coverage, hotspot activity, air quality, and response operations across Indonesia's priority provinces.",statusLabel:"REPORT STATUS",statusBadge:"Monitoring 6 Priority Provinces",updatedAsOf:"UPDATED DATA AS OF",
hotspots:"Total Hotspots",fireSpots:"Fire Spots",sixProvinceAccum:"Accumulated across 6 priority provinces",verifiedOperational:"Operational fire spots",burned24h:"Burned Area — 24h",handledToday:"Area Handled — Today",personnel:"Combined Personnel",responsePersonnel:"Response personnel",affectedKab:"Affected Kab/Kota",reportedCoverage:"Reported affected districts/cities",
situationOverview:"Situation Overview",latestOperational:"Latest operational snapshot for the six priority provinces",priorityScope:"Priority scope",total24h:"Burned area, last 24h",handledGround:"Handled — ground",handledAir:"Handled — air",remainingUncontrolled:"Unextinguished area, 28 Sep",airUnits:"Air units",
impactSummary:"Impact & Response Summary",mainResponseAreas:"Key recorded impacts and response capacity",hotspotActivity:"Hotspot activity",provinceCoverage:"Priority province coverage",sixPriorityText:"Six provinces under priority response.",fieldResponse:"Field response",airOperations:"Air operations",airQuality:"Air quality",airQualityText:"Qualitative air-quality conditions and visibility varied across the six provinces.",weatherContext:"Weather context",weatherContextText:"BMKG linked dry conditions and very strong El Niño influence with elevated karhutla risk.",
provinceCoverageMap:"Province Coverage",provinceCoverageSubtitle:"Priority provinces highlighted on the Indonesia administrative map",mapNote:"The highlighted six provinces are the national priority response area. Fill intensity uses a uniform cumulative burned-area snapshot through 9 August 2026, not today's fire area.",provinceAreaChart:"Burned Area by Priority Province",provinceAreaSubtitle:"Uniform comparison snapshot through 9 August 2026",
hotspotChart:"High-Confidence Hotspots",responseOps:"Response Operations",sortiesToday:"Reported sorties today",personnelComposition:"Combined Personnel Composition",allInstitutions:"Across participating response groups",airQualityPanel:"Air Quality & Visibility",qualitativePanel:"Qualitative conditions reported across the priority provinces",
latestSituation:"Latest Situation",latestSituationSubtitle:"28–29 September 2026 operational update",reportedBurned:"Reported burned area",handledArea:"Handled",unextinguished:"Still unextinguished",comparison:"Change vs 27 Sep",scopeNote:"Daily and cumulative metrics in this report come from different official snapshots. Dates and metric scope are shown so values are not interpreted as if they were from one identical time window.",
timeline:"Karhutla Response Timeline",milestones:"Key monitoring and response milestones",timeline1Title:"National priority response reinforced",timeline1Desc:"BNPB highlighted six priority provinces as the government prepared for elevated August–September karhutla risk.",timeline2Title:"BMKG flagged critical conditions",timeline2Desc:"Dry conditions, very strong El Niño influence and high hotspot activity remained important risk factors.",timeline3Title:"Hotspot concentration & air-quality concerns",timeline3Desc:"BMKG and BNPB reported high hotspot concentrations in Kalimantan and Sumatera, alongside smoke and visibility impacts.",timeline4Title:"Latest six-province operational update",timeline4Desc:"BNPB reported 527.6 ha burned in the latest situation snapshot, 431.53 ha handled and 96.07 ha still unextinguished.",
sources:"Data Sources",sourcesSubtitle:"Official references used by the dashboard and scraper",keywordMatch:"Keyword match",fixedReference:"Fixed reference",snapshot:"Reference snapshot",openSource:"Open source ↗",validationScore:"Relevance score"
},id:{
eyebrow:"ANALISIS DAMPAK KEBAKARAN HUTAN & LAHAN",title:"Karhutla Indonesia 2026",headerDescription:"Situasi, cakupan kebakaran, aktivitas hotspot, kualitas udara, dan operasi penanganan di provinsi prioritas Indonesia.",statusLabel:"STATUS LAPORAN",statusBadge:"Pemantauan 6 Provinsi Prioritas",updatedAsOf:"DATA DIPERBARUI PER",
hotspots:"Total Hotspot",fireSpots:"Fire Spot",sixProvinceAccum:"Akumulasi 6 provinsi prioritas",verifiedOperational:"Fire spot operasional",burned24h:"Luas Terbakar — 24 Jam",handledToday:"Luas Ditangani — Hari Ini",personnel:"Personel Gabungan",responsePersonnel:"Personel penanganan",affectedKab:"Kab/Kota Terdampak",reportedCoverage:"Kabupaten/kota yang dilaporkan terdampak",
situationOverview:"Ringkasan Situasi",latestOperational:"Snapshot operasional terbaru untuk enam provinsi prioritas",priorityScope:"Cakupan prioritas",total24h:"Luas terbakar, 24 jam terakhir",handledGround:"Ditangani — darat",handledAir:"Ditangani — udara",remainingUncontrolled:"Luas belum padam, 28 Sep",airUnits:"Unit udara",
impactSummary:"Ringkasan Dampak & Respons",mainResponseAreas:"Dampak utama dan kapasitas penanganan",hotspotActivity:"Aktivitas hotspot",provinceCoverage:"Cakupan provinsi prioritas",sixPriorityText:"Enam provinsi dalam penanganan prioritas.",fieldResponse:"Respons lapangan",airOperations:"Operasi udara",airQuality:"Kualitas udara",airQualityText:"Kondisi kualitas udara dan jarak pandang bervariasi di enam provinsi.",weatherContext:"Konteks cuaca",weatherContextText:"BMKG mengaitkan kondisi kering dan pengaruh El Niño sangat kuat dengan peningkatan risiko karhutla.",
provinceCoverageMap:"Cakupan Provinsi",provinceCoverageSubtitle:"Provinsi prioritas ditampilkan pada peta administratif Indonesia",mapNote:"Enam provinsi yang disorot merupakan wilayah prioritas penanganan nasional. Intensitas warna memakai snapshot akumulasi luas terbakar hingga 9 Agustus 2026, bukan luas kebakaran hari ini.",provinceAreaChart:"Luas Terbakar per Provinsi Prioritas",provinceAreaSubtitle:"Perbandingan seragam hingga 9 Agustus 2026",
hotspotChart:"Hotspot Kepercayaan Tinggi",responseOps:"Operasi Penanganan",sortiesToday:"Sortie yang dilaporkan hari ini",personnelComposition:"Komposisi Personel Gabungan",allInstitutions:"Dari kelompok/instansi penanganan",airQualityPanel:"Kualitas Udara & Jarak Pandang",qualitativePanel:"Kondisi kualitatif yang dilaporkan di provinsi prioritas",
latestSituation:"Situasi Terbaru",latestSituationSubtitle:"Pembaruan operasional 28–29 September 2026",reportedBurned:"Luas terbakar yang dilaporkan",handledArea:"Ditangani",unextinguished:"Masih belum padam",comparison:"Perubahan vs 27 Sep",scopeNote:"Metrik harian dan kumulatif dalam laporan ini berasal dari snapshot resmi dengan waktu yang berbeda. Tanggal dan cakupan metrik ditampilkan agar nilainya tidak dianggap berasal dari satu periode identik.",
timeline:"Linimasa Penanganan Karhutla",milestones:"Tonggak pemantauan dan penanganan",timeline1Title:"Prioritas nasional diperkuat",timeline1Desc:"BNPB menekankan enam provinsi prioritas saat pemerintah mempersiapkan risiko karhutla Agustus–September.",timeline2Title:"BMKG menandai kondisi kritis",timeline2Desc:"Kondisi kering, pengaruh El Niño sangat kuat, dan aktivitas hotspot menjadi faktor risiko utama.",timeline3Title:"Konsentrasi hotspot & kualitas udara",timeline3Desc:"BMKG dan BNPB melaporkan konsentrasi hotspot tinggi di Kalimantan dan Sumatera, disertai dampak asap dan jarak pandang.",timeline4Title:"Pembaruan operasional enam provinsi",timeline4Desc:"BNPB melaporkan 527,6 ha terbakar pada snapshot terbaru, 431,53 ha ditangani dan 96,07 ha masih belum padam.",
sources:"Sumber Data",sourcesSubtitle:"Referensi resmi yang digunakan dashboard dan scraper",keywordMatch:"Pencarian keyword",fixedReference:"Referensi tetap",snapshot:"Snapshot referensi",openSource:"Buka sumber ↗",validationScore:"Skor relevansi"
}};
function t(k){return I18N[state.lang][k]||I18N.en[k]||k}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function fmt(v,d=1){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat(state.lang==="id"?"id-ID":"en-US",{maximumFractionDigits:d}).format(n):"—"}
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function applyLang(){document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(e=>e.innerHTML=t(e.dataset.i18n));document.querySelectorAll(".lang-button").forEach(b=>b.classList.toggle("active",b.dataset.lang===state.lang));localStorage.setItem("karhutlaDashboardLang",state.lang)}
function destroy(k){if(state.charts[k])state.charts[k].destroy()}
function bar(k,id,labels,data,label,indexAxis="x"){destroy(k);state.charts[k]=new Chart(document.getElementById(id),{type:"bar",data:{labels,datasets:[{label,data,borderRadius:7,backgroundColor:"rgba(234,88,12,.72)",borderColor:"#ea580c",borderWidth:1}]},options:{indexAxis,responsive:true,maintainAspectRatio:false,layout:{padding:{right:indexAxis==="y"?36:10}},plugins:{legend:{display:!!label,position:"bottom"}},scales:{x:{beginAtZero:true,grid:{display:indexAxis==="y"?false:true}},y:{beginAtZero:true,grid:{display:indexAxis==="y"?true:true}}}}})}
function renderKPIs(d){set("kpiHotspots",fmt(d.current.total_hotspots,0));set("kpiFireSpots",fmt(d.current.fire_spots,0));set("kpiBurned24h",fmt(d.current.burned_area_24h_ha,1));set("kpiHandledToday",fmt(d.current.handled_area_today_ha,1));set("kpiPersonnel",fmt(d.current.personnel,0));set("kpiAffectedKab",fmt(d.current.affected_regencies_cities,0));set("statusDate",d.metadata.last_updated_display||"29 September 2026");set("overviewBurned",`${fmt(d.current.burned_area_24h_ha,1)} ha`);set("overviewGround",`${fmt(d.current.handled_area_ground_ha,1)} ha`);set("overviewAir",`${fmt(d.current.handled_area_air_ha,1)} ha`);set("overviewRemaining",`${fmt(d.current.uncontrolled_area_ha,2)} ha`);set("overviewAirUnits",`${fmt(d.current.air_units,0)} units`);set("summaryHotspotText",`${fmt(d.current.total_hotspots,0)} hotspots and ${fmt(d.current.fire_spots,0)} fire spots in the current dashboard snapshot.`);set("summaryPersonnelText",`${fmt(d.current.personnel,0)} combined personnel across participating response groups.`);set("summaryAirText",`${fmt(d.current.air_units,0)} total air units; 9 patrol, 21 water-bombing and 8 OMC sorties are separately reported.`);set("latestTotalBurned",`${fmt(d.current.total_burned_area_situation_ha,1)} ha`);set("latestHandled","431.53 ha");set("latestUnextinguished",`${fmt(d.current.uncontrolled_area_ha,2)} ha`);set("latestChange","−62.29 ha");set("hotspotPeriod",d.hotspot_window_latest?.period||"10–21 September 2026")}
function renderCharts(d){const p=[...(d.priority_provinces||[])].sort((a,b)=>b.burned_area_snapshot_ha-a.burned_area_snapshot_ha);bar("province","provinceAreaChart",p.map(x=>x.name),p.map(x=>x.burned_area_snapshot_ha),"Burned area (ha)","y");const h=d.hotspot_window_latest?.high_confidence||[];bar("hotspots","hotspotChart",h.map(x=>x.province),h.map(x=>x.hotspots),"High-confidence hotspots","y");const o=d.operations_today||[];bar("ops","operationsChart",o.map(x=>x.operation),o.map(x=>x.sorties),"Sorties","x");const pe=(d.personnel_composition||[]).slice().sort((a,b)=>b.count-a.count);bar("personnel","personnelChart",pe.map(x=>x.group),pe.map(x=>x.count),"Personnel","y")}
function renderAir(d){const el=document.getElementById("airQualityGrid");el.innerHTML=(d.province_air_quality||[]).map(x=>{const q=x.air_quality.toLowerCase();let c=q.includes("hazardous")?"danger":q.includes("unhealthy")?"warning":q.includes("moderate")?"moderate":"good";return `<div class="air-card"><div class="air-top"><strong>${esc(x.province)}</strong><span class="air-pill ${c}">${esc(x.air_quality)}</span></div><div class="air-meta">Visibility: ${esc(x.visibility_km)}</div></div>`}).join("")}
async function renderMap(d){const map=L.map("provinceMap").setView([-1,113],4.4);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:8,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);const m=new Map((d.priority_provinces||[]).map(x=>[x.name.toLowerCase(),x]));const u="https://cdn.jsdelivr.net/gh/denyherianto/indonesia-geojson-topojson-maps-with-38-provinces@main/GeoJSON/indonesia-38-provinces.geojson";try{const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error("Boundary HTTP "+r.status);const g=await r.json();const vals=[...m.values()].map(x=>x.burned_area_snapshot_ha),mx=Math.max(...vals),mn=Math.min(...vals);const color=v=>{if(!v)return"#eef2f6";const z=(v-mn)/(mx-mn||1);return z>.7?"#c2410c":z>.35?"#ea580c":"#fb923c"};const layer=L.geoJSON(g,{style:f=>{const n=String(f.properties?.PROVINSI||"").toLowerCase(),x=m.get(n);return x?{color:"#9a3412",weight:1.2,fillColor:color(x.burned_area_snapshot_ha),fillOpacity:.62}:{color:"#d5dce5",weight:.6,fillColor:"#f1f5f9",fillOpacity:.42}},onEachFeature:(f,l)=>{const n=f.properties?.PROVINSI||"Unknown";const x=m.get(String(n).toLowerCase());if(x)l.bindPopup(`<div class="map-popup-title">${esc(n)}</div><div class="map-popup-text"><strong>Priority response area</strong><br>Burned-area snapshot through 9 Aug 2026: ${fmt(x.burned_area_snapshot_ha,2)} ha</div>`);else l.bindTooltip(esc(n),{sticky:true})}}).addTo(map);const b=layer.getBounds();if(b.isValid())map.fitBounds(b,{padding:[18,18],maxZoom:5})}catch(e){console.warn(e);(d.priority_provinces||[]).forEach(x=>L.circle([x.lat,x.lng],{radius:95000,fillColor:"#ea580c",color:"#9a3412",fillOpacity:.25,weight:1}).bindPopup(`<div class="map-popup-title">${esc(x.name)}</div><div class="map-popup-text">Priority response area<br>Snapshot burned area: ${fmt(x.burned_area_snapshot_ha,2)} ha</div>`).addTo(map))}setTimeout(()=>map.invalidateSize(),100)}
function renderSources(d){document.getElementById("sourceList").innerHTML=(d.sources||[]).map(s=>{const key=s.reference_type==="keyword_match";return `<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><div class="source-card-top"><span class="source-badge">${key?t("keywordMatch"):t("fixedReference")}</span><span class="source-status ${s.fetch_status==="OK"?"green":"amber"}">● ${s.fetch_status==="OK"?"Source available":t("snapshot")}</span></div><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p><div class="source-meta">${t("validationScore")}: ${fmt(s.relevance_score,0)} / ${fmt(s.validation_threshold,0)}</div><div class="source-link">${t("openSource")}</div><div class="source-url">${esc(s.url)}</div></a>`}).join("")}
async function init(){const r=await fetch("data/karhutla_2026.json",{cache:"no-store"});if(!r.ok)throw new Error("Could not load data JSON");state.data=await r.json();applyLang();renderKPIs(state.data);renderCharts(state.data);renderAir(state.data);renderSources(state.data);renderMap(state.data)}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".lang-button").forEach(b=>b.addEventListener("click",()=>{state.lang=b.dataset.lang;applyLang();if(state.data){renderKPIs(state.data);renderCharts(state.data);renderAir(state.data);renderSources(state.data)}}));init().catch(e=>document.querySelector("main").insertAdjacentHTML("afterbegin",`<div class="error-box">${esc(e.message)}</div>`))});
